In [2]:
import numpy as np
import pandas as pd
import lightgbm as lgb

In [1]:
import os

In [5]:
data_files = os.listdir(rf"D:\Work\stocks\stocks_processed\USA")

In [55]:
x_trains = []
y_trains = {"1": [], "2": [], "3": []}
x_vals = {"1": [], "2": [], "3": []}
y_vals = {"1": [], "2": [], "3": []}
val_date = "2021-01-01"
for data_file in data_files[:1]:
    data = pd.read_csv(f"D:\\Work\\stocks\\stocks_processed\\USA\\{data_file}", index_col="Date", parse_dates=['Date'])
    target = pd.DataFrame()
    for i in range(1, 10):
        target[f"t-{i}"] = data["Close"].shift(-i)
    target = target[30:]
    x = []
    for i in range(data.shape[0] - 30):
        x.append(data[i:i + 30].to_numpy().flatten())
    x = np.array(x)
    val_indx = data[:val_date].shape[0]
    train_data = x[:val_indx]
    x_trains.append(train_data)
    val_data = x[val_indx:]
    train_target = target[:val_indx]
    val_target = target[val_indx:]
    for i in range(3):
        y_trains[f"{i + 1}"].append(train_target[[f"t-{i*3 + 1}", f"t-{i*3 + 2}", f"t-{i*3 + 3}"]])
        y_vals[f"{i + 1}"].append(val_target[[f"t-{i * 3 + 1}", f"t-{i * 3 + 2}", f"t-{i * 3 + 3}"]][:-3*(i + 1)])
        x_vals[f"{i + 1}"].append(val_data[:-3*(i + 1)])

In [58]:
x_train = x_trains[0]

In [60]:
x_train_df = pd.DataFrame(x_train)

In [57]:
x_vals["1"][0].shape

(470, 1170)

In [13]:
data[2:32].to_numpy().flatten().shape

(1170,)

In [ ]:
data["2021-01-01":].shape

(503, 39)

In [38]:
data[0:30].to_numpy().flatten().shape

(1170,)

In [43]:
x = []
for i in range(data.shape[0] - 30):
    x.append(data[i:i + 30].to_numpy().flatten())

In [45]:
x = np.array(x)

In [46]:
x.shape

(5558, 1170)

In [2]:
X = np.random.rand(100, 10)
y = np.random.rand(100, 3)
y[X[:,3] > 0.5] += 3
y[X[:,6] > 0.8] -= 10
y[X[:,1] < 0.25] += 5

In [3]:
m = xg.XGBRegressor(n_estimators=4, max_depth=2)

In [4]:
m.fit(X, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=2, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=4, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [7]:
y_mean = y.mean(axis=0)

In [8]:
y_mean

array([1.2603546 , 1.27683579, 1.25711134])

In [9]:
((y - y_mean) ** 2).sum(axis=0)

array([2311.55261625, 2392.86392452, 2308.93990908])

In [10]:
p = m.predict(X)

In [12]:
((y - p) ** 2).sum(axis=0)

array([287.91019797, 297.98594799, 289.56598474])